# Generated by Django 2.2 on 2021-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='category',
            field=models.CharField(default='tri', max_length=8),
        ),
    ]
